### ISSUE TITLE
When to release 2.3.2?

### ISSUE THREAD

**Issue by minggo** [erincatto/box2d#478] opened 2017-11-01 01:47 UTC
Box2D 2.3.1 is released 3 years ago, is there any plan to release v2.3.2?

Thanks.

**Comment by minggo** [comment] 2017-11-01 02:36
Can is use latest codes in products?

**Comment by minggo** [comment] 2017-11-01 02:38
@erincatto could you please take a look? [cocos2d-x](https://github.com/cocos2d/cocos2d-x) integrates Box2D, some developers of cocos2d-x ask to update Box2D to latest commit, but i am not sure if it is suitable.

Thanks.

**Comment by louis-langholtz** [comment] 2017-11-01 02:39
Based on the contents of [b2Settings.cpp](https://github.com/erincatto/Box2D/blob/master/Box2D/Box2D/Common/b2Settings.cpp), I've been calling what's currently available 2.3.2. I see now though that in git tag terms, there isn't a v2.3.2 tag yet. Have I been wrong called the head code 2.3.2 then perhaps?

**Comment by minggo** [comment] 2017-11-01 02:41
I am not sure, because the version is changed after releasing 2.3.1, which is also 3 years ago.

**Comment by KAMIKAZEUA** [comment] 2017-11-08 13:15
@erincatto I'm using latest code commit of Box2D in my complex games and got no problems. However, with older versions I got some crashes, so I definitely think that 2.3.2 aka latest commit code is stable.

**Comment by erincatto** [comment] 2018-05-27 22:45
Lately I have only been fixing bugs, so master should be the most stable version of Box2D. I have not had time to do a proper release.

**Comment by igor-sadchenko** [comment] 2019-10-15 09:40
@erincatto could you set new tag 2.3.2rc on the latest commit in master?
It will take little time.

**Comment by erincatto** [comment] 2020-04-15 06:45
Current working on 2.4.0.

**Comment by erincatto** [comment] 2020-07-17 06:34
Duplicate of #431

**Closed by erincatto** 2020-07-17 06:34 UTC
Labels: question
