### ISSUE TITLE
Unnecessary friend class declaration (b2RopeJoint)

### ISSUE THREAD

**Issue by Reputeless** [erincatto/box2d#680] opened 2021-03-24 04:16 UTC
https://github.com/erincatto/box2d/blob/95f74a46c077825478f989df6a81003ca538c2c2/include/box2d/b2_body.h#L404

`b2RopeJoint` was removed in v2.4.1.

**Comment by erincatto** [comment] 2021-12-29 06:52
Duplicate of #665

**Closed by erincatto** 2021-12-29 06:52 UTC
