### ISSUE TITLE
Feature request: runtime-configurable b2_velocityThreshold

### ISSUE THREAD

**Issue by AshleyScirra** [erincatto/box2d#601] opened 2020-06-02 14:24 UTC
We build a game engine that includes Box2D, and many different types of games are built with our engine.

However some games need to alter `b2_velocityThreshold` - notably pool/billiards type games, to get the right ball bounce direction at low velocities.

Unfortunately `b2_velocityThreshold` is a build-time constant. We can only change it once for all games used by our engine. I would expect that there is some rationale for the default and if we just change it for everyone it will break other cases that depend on the default.

Could it perhaps be updated to be a property of b2World instead?

**Comment by erincatto** [comment] 2020-07-17 06:36
Duplicate of #559

**Comment by erincatto** [comment] 2020-09-13 23:31
Run-time settings

**Comment by erincatto** [comment] 2020-10-11 04:25
Implemented in #654

**Closed by erincatto** 2020-10-11 04:25 UTC
